db.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
db.host=localhost
db.port=1433
db.name=disaster_mis
db.username=SA
db.password=reallyStrongPwd123
db.encrypt=true
db.trustServerCertificate=true
